export const dummyLastTransactions = [
  {
    date: "07-02-2023",
    name: "Bessie Cooper",
    avatar: "https://i.pravatar.cc/150?img=1",
    status: "PAYOUT",
    currency: "USD",
    amount: 3000,
  },
  {
    date: "07-02-2023",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?img=2",
    status: "PAYIN",
    currency: "USD",
    amount: 1970,
  },
  {
    date: "07-02-2023",
    name: "Floyd Miles",
    avatar: "https://i.pravatar.cc/150?img=3",
    status: "PAYOUT",
    currency: "USD",
    amount: 5000,
  },
  {
    date: "07-02-2023",
    name: "Bessie Cooper",
    avatar: "https://i.pravatar.cc/150?img=4",
    status: "PAYOUT",
    currency: "USD",
    amount: 3000,
  },
  {
    date: "07-02-2023",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?img=5",
    status: "PAYIN",
    currency: "USD",
    amount: 1970,
  },
  {
    date: "07-02-2023",
    name: "Floyd Miles",
    avatar: "https://i.pravatar.cc/150?img=6",
    status: "PAYOUT",
    currency: "USD",
    amount: 5000,
  },
  {
    date: "07-02-2023",
    name: "Bessie Cooper",
    avatar: "https://i.pravatar.cc/150?img=7",
    status: "PAYOUT",
    currency: "USD",
    amount: 3000,
  },
  {
    date: "07-02-2023",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?img=8",
    status: "PAYIN",
    currency: "USD",
    amount: 1970,
  },
  {
    date: "07-02-2023",
    name: "Floyd Miles",
    avatar: "https://i.pravatar.cc/150?img=9",
    status: "PAYOUT",
    currency: "USD",
    amount: 5000,
  },
  {
    date: "07-02-2023",
    name: "Bessie Cooper",
    avatar: "https://i.pravatar.cc/150?img=10",
    status: "PAYOUT",
    currency: "USD",
    amount: 3000,
  },
  {
    date: "07-02-2023",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?img=11",
    status: "PAYIN",
    currency: "USD",
    amount: 1970,
  },
  {
    date: "07-02-2023",
    name: "Floyd Miles",
    avatar: "https://i.pravatar.cc/150?img=12",
    status: "PAYOUT",
    currency: "USD",
    amount: 5000,
  },
  {
    date: "07-02-2023",
    name: "Bessie Cooper",
    avatar: "https://i.pravatar.cc/150?img=13",
    status: "PAYOUT",
    currency: "USD",
    amount: 3000,
  },
  {
    date: "07-02-2023",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?img=14",
    status: "PAYIN",
    currency: "USD",
    amount: 1970,
  },
];
